# Generated by Django 5.0 on 2023-12-28 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription_date', models.DateField()),
                ('patient_name', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('patient_category', models.CharField(choices=[('Inpatient', 'Inpatient'), ('Outpatient', 'Outpatient'), ('Pediatric', 'Pediatric'), ('Geriatric', 'Geriatric')], max_length=50)),
                ('doctor_name', models.CharField(max_length=255)),
                ('doctor_designation', models.CharField(max_length=100)),
                ('doctor_contact_number', models.CharField(max_length=15)),
                ('contact_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('diagnostic_center', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_name', models.CharField(max_length=100)),
                ('dose', models.CharField(max_length=50)),
                ('dose_time', models.CharField(max_length=50)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthapp.patient')),
            ],
        ),
    ]
