# Generated by Django 5.0 on 2023-12-28 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_id', models.CharField(default='d00x', max_length=255)),
                ('doctor_name', models.CharField(max_length=255)),
                ('doctor_designation', models.CharField(max_length=100)),
                ('doctor_contact_number', models.CharField(max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='patient',
            name='doctor_contact_number',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='doctor_designation',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='doctor_name',
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_id',
            field=models.CharField(default='p00x', max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='prescription_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='dose_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='doctor_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='healthapp.doctor'),
        ),
    ]
