# Generated by Django 5.0 on 2023-12-31 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0003_remove_patient_prescription_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='drug_name',
            field=models.CharField(choices=[('isoniazid', 'Isoniazid'), ('rifampin ', 'Rifampin '), ('pyrazinamide ', 'Pyrazinamide'), ('ethambutol', 'Ethambutol '), ('streptomycin ', 'Streptomycin')], default='rifampin', max_length=200),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='taken_time',
            field=models.CharField(choices=[('morning', 'Morning'), ('midday', 'Midday'), ('night', 'Night')], default='morning', max_length=200),
        ),
    ]
