# Generated by Django 5.0 on 2023-12-31 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0004_alter_prescription_drug_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='taken_time',
        ),
        migrations.AddField(
            model_name='prescription',
            name='taken_time1',
            field=models.CharField(blank=True, choices=[('morning', 'Morning'), ('midday', 'Midday'), ('night', 'Night')], default='None', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='taken_time2',
            field=models.CharField(blank=True, choices=[('morning', 'Morning'), ('midday', 'Midday'), ('night', 'Night')], default='None', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='taken_time3',
            field=models.CharField(blank=True, choices=[('morning', 'Morning'), ('midday', 'Midday'), ('night', 'Night')], default='None', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
